//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GarageManager
{
    using System;
    using System.Collections.Generic;
    
    public partial class Purchase
    {
        public int ID { get; set; }
        public string CustomerID { get; set; }
        public int ProductID { get; set; }
        public int Amount { get; set; }
        public System.DateTime Date { get; set; }
        public bool IsInCart { get; set; }
    }
}
