//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GarageManager
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserInformation
    {
        public int ID { get; set; }
        public string GUID { get; set; }
        public string firstName { get; set; }
        public string lastName { get; set; }
        public string Address { get; set; }
        public string PostalCode { get; set; }
    }
}
